#!/usr/bin/env bash
# This script is displaying script that gives you information about the holbertonschool file.
if [ -e "Bestschool" ]
then
  echo "Bestschool file exists"
  if [ -s "Bestschool" ]
    then
      echo "Bestschool file is not empty"
    else
      echo "Bestschool file is empty"
  fi

  if [ -f "Bestschool" ]
  then
    echo "Bestschool is a regular file"
  fi
  else
    echo "Bestschool file does not exist"
fi
